package asura.core.es.model

object FieldKeys {

  val FIELD_ID = "id"
  val FIELD_SUMMARY = "summary"
  val FIELD_DESCRIPTION = "description"
  val FIELD_CREATOR = "creator"
  val FIELD_CREATED_AT = "createdAt"
  val FIELD_PATH = "path"
  val FIELD_GROUP = "group"
  val FIELD_PROJECT = "project"
  val FIELD_TYPE = "type"
  val FIELD_SCHEMA = "schema"
  val FIELD_API = "api"
  val FIELD_REQUEST = "request"
  val FIELD_ASSERT = "assert"
  val FIELD_MAP = "map"
  val FIELD_SRC_HOST = "srcHost"
  val FIELD_SRC_PORT = "srcPort"
  val FIELD_TARGET_HOST = "targetHost"
  val FIELD_TARGET_PORT = "targetPort"
  val FIELD_METHOD = "method"
  val FIELD_QUERY = "query"
  val FIELD_HEADER = "header"
  val FIELD_COOKIE = "cookie"
  val FIELD_CONTENT_TYPE = "contentType"
  val FIELD_BODY = "body"
  val FIELD_KEY = "key"
  val FIELD_VALUE = "value"
  val FIELD_VERSION = "version"
  val FIELD_NAME = "name"
  val FIELD_LABELS = "labels"
  val FIELD_DEPRECATED = "deprecated"
  val FIELD_ENABLED = "enabled"
  val FIELD_DEFAULT = "default"
  val FIELD_PROTOCOL = "protocol"
  val FIELD_HOST = "host"
  val FIELD_PORT = "port"
  val FIELD_AUTH = "auth"
  val FIELD_DATA = "data"
  val FIELD_ENV = "env"
  val FIELD_USE_ENV = "useEnv"
  val FIELD_CLASS_ALIAS = "classAlias"
  val FIELD_TRIGGER = "trigger"
  val FIELD_CRON = "cron"
  val FIELD_START_NOW = "startNow"
  val FIELD_START_DATE = "startDate"
  val FIELD_END_DATE = "endDate"
  val FIELD_REPEAT_COUNT = "repeatCount"
  val FIELD_INTERVAL = "interval"
  val FIELD_TRIGGER_TYPE = "triggerType"
  val FIELD_JOB_NAME = "jobName"
  val FIELD_JOB_DATA = "jobData"
  val FIELD_SCHEDULER = "scheduler"
  val FIELD_CS = "cs"
  val FIELD_SCENARIO = "scenario"
  val FIELD_EXT = "ext"
  val FIELD_START_AT = "startAt"
  val FIELD_END_AT = "endAt"
  val FIELD_ELAPSE = "elapse"
  val FIELD_RESULT = "result"
  val FIELD_ERROR_MSG = "errorMsg"
  val FIELD_NODE = "node"
  val FIELD_SERVICE = "service"
  val FIELD_NAMESPACE = "namespace"
  val FIELD_USE_PROXY = "useProxy"
  val FIELD_CASES = "cases"
  val FIELD_AVATAR = "avatar"

  /** copied from [[FIELD_SUMMARY]] and [[FIELD_DESCRIPTION]] */
  val FIELD__TEXT = "_text"
  val FIELD__ID = "_id"
}
