package asura.core.cs


/** used for override default case runtime behavior
  *
  * this can be generated by job ci api url
  *
  * @param env ref [[asura.core.es.model.Environment]]
  */
case class ContextOptions(
                           env: Option[String] = None,
                         ) {

}
