# 1. 添加注释和默认值(不保证默认值的正确性)
# 2. 移除外键

CREATE TABLE QRTZ_JOB_DETAILS
(
    SCHED_NAME        VARCHAR(48)  NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    JOB_NAME          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'JOB_NAME',
    JOB_GROUP         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'JOB_GROUP',
    DESCRIPTION       VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'DESCRIPTION',
    JOB_CLASS_NAME    VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'JOB_CLASS_NAME',
    IS_DURABLE        VARCHAR(1)   NOT NULL DEFAULT '' COMMENT 'IS_DURABLE',
    IS_NONCONCURRENT  VARCHAR(1)   NOT NULL DEFAULT '' COMMENT 'IS_NONCONCURRENT',
    IS_UPDATE_DATA    VARCHAR(1)   NOT NULL DEFAULT '' COMMENT 'IS_UPDATE_DATA',
    REQUESTS_RECOVERY VARCHAR(1)   NOT NULL DEFAULT '' COMMENT 'REQUESTS_RECOVERY',
    JOB_DATA          BLOB         NULL COMMENT 'JOB_DATA',
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_J_REQ_RECOVERY (SCHED_NAME, REQUESTS_RECOVERY),
    KEY IDX_QRTZ_J_GRP (SCHED_NAME, JOB_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'JOB_DETAILS';

CREATE TABLE QRTZ_TRIGGERS
(
    SCHED_NAME     VARCHAR(48)  NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    TRIGGER_NAME   VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_NAME',
    TRIGGER_GROUP  VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    JOB_NAME       VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'JOB_NAME',
    JOB_GROUP      VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'JOB_GROUP',
    DESCRIPTION    VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'DESCRIPTION',
    NEXT_FIRE_TIME BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'NEXT_FIRE_TIME',
    PREV_FIRE_TIME BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'PREV_FIRE_TIME',
    PRIORITY       INTEGER      NOT NULL DEFAULT '0' COMMENT 'PRIORITY',
    TRIGGER_STATE  VARCHAR(12)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_STATE',
    TRIGGER_TYPE   VARCHAR(8)   NOT NULL DEFAULT '' COMMENT 'TRIGGER_TYPE',
    START_TIME     BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'START_TIME',
    END_TIME       BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'END_TIME',
    CALENDAR_NAME  VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'CALENDAR_NAME',
    MISFIRE_INSTR  SMALLINT(2)  NOT NULL DEFAULT '0' COMMENT 'MISFIRE_INSTR',
    JOB_DATA       BLOB         NULL COMMENT 'JOB_DATA',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_T_J (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_T_JG (SCHED_NAME, JOB_GROUP),
    KEY IDX_QRTZ_T_C (SCHED_NAME, CALENDAR_NAME),
    KEY IDX_QRTZ_T_G (SCHED_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_T_STATE (SCHED_NAME, TRIGGER_STATE),
    KEY IDX_QRTZ_T_N_STATE (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    KEY IDX_QRTZ_T_N_G_STATE (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    KEY IDX_QRTZ_T_NEXT_FIRE_TIME (SCHED_NAME, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_ST (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_MISFIRE (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_ST_MISFIRE (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE),
    KEY IDX_QRTZ_T_NFT_ST_MISFIRE_GRP (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'TRIGGERS';

CREATE TABLE QRTZ_SIMPLE_TRIGGERS
(
    SCHED_NAME      VARCHAR(48) NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    TRIGGER_NAME    VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'TRIGGER_NAME',
    TRIGGER_GROUP   VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    REPEAT_COUNT    BIGINT(7)   NOT NULL DEFAULT '0' COMMENT 'REPEAT_COUNT',
    REPEAT_INTERVAL BIGINT(12)  NOT NULL DEFAULT '0' COMMENT 'REPEAT_INTERVAL',
    TIMES_TRIGGERED BIGINT(10)  NOT NULL DEFAULT '0' COMMENT 'TIMES_TRIGGERED',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'SIMPLE_TRIGGERS';

CREATE TABLE QRTZ_CRON_TRIGGERS
(
    SCHED_NAME      VARCHAR(48)  NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    TRIGGER_NAME    VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_NAME',
    TRIGGER_GROUP   VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    CRON_EXPRESSION VARCHAR(120) NOT NULL DEFAULT '' COMMENT 'CRON_EXPRESSION',
    TIME_ZONE_ID    VARCHAR(80)  NOT NULL DEFAULT '' COMMENT 'TIME_ZONE_ID',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'CRON_TRIGGERS';

CREATE TABLE QRTZ_SIMPROP_TRIGGERS
(
    SCHED_NAME    VARCHAR(48)    NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    TRIGGER_NAME  VARCHAR(64)    NOT NULL DEFAULT '' COMMENT 'TRIGGER_NAME',
    TRIGGER_GROUP VARCHAR(64)    NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    STR_PROP_1    VARCHAR(512)   NOT NULL DEFAULT '' COMMENT 'STR_PROP_1',
    STR_PROP_2    VARCHAR(512)   NOT NULL DEFAULT '' COMMENT 'STR_PROP_2',
    STR_PROP_3    VARCHAR(512)   NOT NULL DEFAULT '' COMMENT 'STR_PROP_3',
    INT_PROP_1    INT            NOT NULL DEFAULT '0' COMMENT 'INT_PROP_1',
    INT_PROP_2    INT            NOT NULL DEFAULT '0' COMMENT 'INT_PROP_2',
    LONG_PROP_1   BIGINT         NOT NULL DEFAULT '0' COMMENT 'LONG_PROP_1',
    LONG_PROP_2   BIGINT         NOT NULL DEFAULT '0' COMMENT 'LONG_PROP_2',
    DEC_PROP_1    NUMERIC(13, 4) NOT NULL DEFAULT '0.0' COMMENT 'DEC_PROP_1',
    DEC_PROP_2    NUMERIC(13, 4) NOT NULL DEFAULT '0.0' COMMENT 'DEC_PROP_2',
    BOOL_PROP_1   VARCHAR(1)     NOT NULL DEFAULT '' COMMENT 'BOOL_PROP_1',
    BOOL_PROP_2   VARCHAR(1)     NOT NULL DEFAULT '' COMMENT 'BOOL_PROP_2',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'SIMPROP_TRIGGERS';

CREATE TABLE QRTZ_BLOB_TRIGGERS
(
    SCHED_NAME    VARCHAR(48) NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    TRIGGER_NAME  VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'TRIGGER_NAME',
    TRIGGER_GROUP VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    BLOB_DATA     BLOB        NULL COMMENT 'BLOB_DATA',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'BLOB_TRIGGERS';

CREATE TABLE QRTZ_CALENDARS
(
    SCHED_NAME    VARCHAR(48) NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    CALENDAR_NAME VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'CALENDAR_NAME',
    CALENDAR      BLOB        NULL COMMENT 'CALENDAR',
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'CALENDARS';

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS
(
    SCHED_NAME    VARCHAR(48) NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    TRIGGER_GROUP VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'PAUSED_TRIGGER_GRPS';

CREATE TABLE QRTZ_FIRED_TRIGGERS
(
    SCHED_NAME        VARCHAR(48)  NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    ENTRY_ID          VARCHAR(95)  NOT NULL DEFAULT '' COMMENT 'ENTRY_ID',
    TRIGGER_NAME      VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_NAME',
    TRIGGER_GROUP     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'TRIGGER_GROUP',
    INSTANCE_NAME     VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'INSTANCE_NAME',
    FIRED_TIME        BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'FIRED_TIME',
    SCHED_TIME        BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'SCHED_TIME',
    PRIORITY          INTEGER      NOT NULL DEFAULT '0' COMMENT 'PRIORITY',
    STATE             VARCHAR(16)  NOT NULL DEFAULT '' COMMENT 'STATE',
    JOB_NAME          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'JOB_NAME',
    JOB_GROUP         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT 'JOB_GROUP',
    IS_NONCONCURRENT  VARCHAR(1)   NOT NULL DEFAULT '' COMMENT 'IS_NONCONCURRENT',
    REQUESTS_RECOVERY VARCHAR(1)   NOT NULL DEFAULT '' COMMENT 'REQUESTS_RECOVERY',
    PRIMARY KEY (SCHED_NAME, ENTRY_ID),
    KEY IDX_QRTZ_FT_TRIG_INST_NAME (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY),
    KEY IDX_QRTZ_FT_INST_JOB_REQ_RCVRY (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_FT_J_G (SCHED_NAME, JOB_GROUP),
    KEY IDX_QRTZ_FT_JG (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_FT_TG (SCHED_NAME, TRIGGER_GROUP)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'FIRED_TRIGGERS';

CREATE TABLE QRTZ_SCHEDULER_STATE
(
    SCHED_NAME        VARCHAR(48)  NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    INSTANCE_NAME     VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'INSTANCE_NAME',
    LAST_CHECKIN_TIME BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'LAST_CHECKIN_TIME',
    CHECKIN_INTERVAL  BIGINT(13)   NOT NULL DEFAULT '0' COMMENT 'CHECKIN_INTERVAL',
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'SCHEDULER_STATE';

CREATE TABLE QRTZ_LOCKS
(
    SCHED_NAME VARCHAR(48) NOT NULL DEFAULT '' COMMENT 'SCHED_NAME',
    LOCK_NAME  VARCHAR(40) NOT NULL DEFAULT '' COMMENT 'LOCK_NAME',
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT = 'LOCKS';
